project:
  type: website

website:
  title: "Grimire"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mazzma12/grimoire
      - icon: twitter
        href: https://twitter.com/mazzma12
format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css



